[build]
target = "x86_64-sh_os.json"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[target.'cfg(all(target_arch = "x86_64", target_os = "none"))']
runner = "bootimage runner"
